### ISSUE TITLE
Improve ease of use

### ISSUE THREAD

**Issue by garima-bothra** [abadikaka/SFSymbolsFinder#8]
**Is your feature request related to a problem? Please describe.**
I find it inconvenient to use SFSmybols as: `Commerce.bagBadgePlus.image`. It does not feel intuitive and I always make a mistake when trying to use this.

**Describe the solution you'd like**
It would be more convenient and intuitive if the image could be accessed as `imagename()`

**Comment by garima-bothra** [comment]
I would like to work on this @abadikaka

**Comment by abadikaka** [comment]
@garima94921 for that particular area, it is for a category enum same as the SF Symbols App. If you want access for all enum you can use All
But also i just released today new update that actually you can directly use Image(systemName: .badgeBagPlus) which is most convenient

However feel free to add better descriptive getter method like imageName() if you wish I will review it, that is okay. We can use it for UIKit purpose too
Feel free open PR and I can start check and comment start from there

**Comment by garima-bothra** [comment]
My issue here was not the category but adding`.image` at the end. A getter method like `Commerce.bagBadgePlus()` for the previous example would be more intuitive.

I will open a PR for the same

**Comment by abadikaka** [comment]
Sure feel free open the PR @garima94921
