### ISSUE TITLE
Feature Request - Modifying Naming Convention for Icons

### ISSUE THREAD

**Issue by garima-bothra** [abadikaka/SFSymbolsFinder#9]
**Is your feature request related to a problem? Please describe.**
It is not obvious to use SF Symbols as - `All.applelogo` (for icons that do not belong to a particular category)

**Describe the solution you'd like**
A possible solution would be searching as - `SFSymbols.imagename`

**Describe alternatives you've considered**
An alternative solution could be adding `SFSymbolsFinder.All.imagename` and likewise for all categories.

**Comment by abadikaka** [comment]
using `SFSymbols` is my first initial thought, you can make a new enum for it  with `SFSymbols`. At first because I already have other categories, so I use All as general category.. feel free to open PR @garima94921
